# Generated by Django 5.2.8 on 2025-12-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
