# Generated by Django 5.2.8 on 2025-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit', models.CharField(max_length=50)),
                ('min_amount', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductHint',
            fields=[
                ('product_hint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'products_hints',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('product_ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'products_ingredients',
            },
        ),
    ]
