# Generated by Django 5.2.8 on 2025-11-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='producthint',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='producthint',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
    ]
