# Generated by Django 5.2.8 on 2025-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_producthint_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
